version: "3.3"
services:
  myapp:
    build: ./Docker_React/
    image: mfrony2003/app_cicd:new
    ports:
      - "3000:3000"
    links:
      - "myapi"





  myapi:
    build: ./Docker_NodeAPI/
    image: mfrony2003/api_cicd:new
    ports:
      - "3001:3001"
