version: "3.3"
services:
  myapp:
    build: ./Docker_React/
    image: app_cicd
    ports:
      - "3000:3000"
    links:
      - "myapi"





  myapi:
    build: ./Docker_NodeAPI/
    image: api_cicd
    ports:
      - "3001:3001"
