name: ciAPP 
on:
 push:
   branches: master
 
jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     - name: print
       env:
          Docker_React: Docker_React
          run: echo "$Docker_React"                       
          
     - name: checkout
       uses: actions/checkout@v2
       with:
          fetch-depth: 0
     - name: getCommitFile
       id: getfile
       run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u)"
          
      

     - name: Login to DockerHub
       if: ${{steps.getfile.outputs.files == $Docker_React}}       
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}       
     
     
     

     - name: Build and push api
       id: docker_build_app       
       if: ${{steps.getfile.outputs.files == $Docker_React}}          
       uses: docker/build-push-action@v2       
       with:
         file: /Docker_React/Dockerfile
         push: true
         tags: mfrony2003/api_cicd:latest

     
     